version: '3.8'

services:
  api:
    build:
      context: .
      dockerfile: ./compose/local/fastapi/Dockerfile
    image: getkendy/kendy-fastapi:latest
    # '/start' is the shell script used to run the service
    command: /start
    # this volume is used to map the files and folders on the host to the container
    # so if we change code on the host, code in the docker container will also be changed
    volumes:
      - .:/app
    ports:
      - 8000:8000
    env_file:
      - .env/.dev-sample
    depends_on:
      - redis
      - mongo
    restart: unless-stopped

  
  mongo:
    image: mongo:latest
    volumes:
      - mongo_data:/data/db
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=p@ssword
    ports:
      - 27017:27017
    restart: unless-stopped

  redis:
    image: redis:6-alpine
    restart: unless-stopped

  celery_worker1:
    build:
      context: .
      dockerfile: ./compose/local/fastapi/Dockerfile
    image: getkendy/kendy-fastapi:latest
    command: /start-celeryworker1
    volumes:
      - .:/app
    env_file:
      - .env/.dev-sample
    depends_on:
      - redis
      - mongo
    restart: unless-stopped
  celery_worker2:
    build:
      context: .
      dockerfile: ./compose/local/fastapi/Dockerfile
    image: getkendy/kendy-fastapi:latest
    command: /start-celeryworker2
    volumes:
      - .:/app
    env_file:
      - .env/.dev-sample
    depends_on:
      - redis
      - mongo
    restart: unless-stopped

  celery_beat:
    build:
      context: .
      dockerfile: ./compose/local/fastapi/Dockerfile
    image: getkendy/kendy-fastapi:latest
    command: /start-celerybeat
    volumes:
      - .:/app
    env_file:
      - .env/.dev-sample
    depends_on:
      - redis
      - mongo
    restart: unless-stopped

  flower:
    build:
      context: .
      dockerfile: ./compose/local/fastapi/Dockerfile
    image: getkendy/kendy-fastapi:latest
    command: /start-flower
    volumes:
      - .:/app
    env_file:
      - .env/.dev-sample
    ports:
      - 5555:5555
    depends_on:
      - redis
      - mongo
    restart: unless-stopped

volumes:
  mongo_data:
  